name: AI Workflow Collaborator

on:
  # Run on any workflow changes
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'scripts/**'
      - 'requirements.txt'
  
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'scripts/**'
      - 'requirements.txt'
  
  # Run daily to ensure workflows stay healthy
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 UTC
  
  # Allow manual triggers
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check-and-fix-workflows:
    name: AI Workflow Health Check & Fix
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Create results directory
        run: |
          mkdir -p results
      
      - name: Run AI Workflow Health Checker
        id: health_check
        run: |
          python scripts/ai_workflow_health_checker.py
        continue-on-error: true
      
      - name: Run AI Workflow Fixer
        if: steps.health_check.outcome == 'failure'
        id: fixer
        run: |
          python scripts/ai_workflow_fixer.py
        continue-on-error: true
      
      - name: Check if fixes were applied
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain .github/workflows/)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "🔧 Workflow fixes were applied"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "✅ No workflow changes needed"
          fi
      
      - name: Commit and push fixes
        if: steps.check_changes.outputs.changes == 'true' && github.event_name != 'pull_request'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "AI Workflow Collaborator[bot]"
          git add .github/workflows/
          git add scripts/
          git commit -m "🤖 AI Workflow Collaborator: Auto-fix workflow issues

          Applied automated fixes to ensure workflows pass correctly.
          
          - Fixed by: AI Workflow Fixer
          - Date: $(date -u +%Y-%m-%d\ %H:%M:%S) UTC
          
          [skip ci]" || echo "No changes to commit"
          git push
      
      - name: Create PR with fixes
        if: steps.check_changes.outputs.changes == 'true' && github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "🤖 AI Workflow Collaborator: Auto-fix workflow issues"
          title: "🤖 AI Workflow Fixes"
          body: |
            ## 🤖 AI Workflow Collaborator Report
            
            This PR contains automated fixes applied by the AI Workflow Collaborator to ensure all workflows pass correctly and badges show GREEN ✅.
            
            ### Fixes Applied
            
            See the workflow health and fix reports in the artifacts for details.
            
            ### What to do
            
            1. Review the changes
            2. Test the workflows
            3. Merge if everything looks good
            
            ---
            *Generated by AI Workflow Collaborator*
          branch: ai-workflow-fixes
          labels: |
            automated
            ci/cd
            workflow-fix
      
      - name: Upload health report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: workflow-health-report
          path: |
            results/workflow_health_report.json
            results/workflow_fix_report.json
          retention-days: 30
      
      - name: Upload workflow backups
        uses: actions/upload-artifact@v4
        if: steps.check_changes.outputs.changes == 'true'
        with:
          name: workflow-backups
          path: .github/workflow_backups/
          retention-days: 90
      
      - name: Generate summary
        if: always()
        run: |
          echo "## 🤖 AI Workflow Collaborator Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f "results/workflow_health_report.json" ]; then
            echo "### Workflow Health Report" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            cat results/workflow_health_report.json | head -50 >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f "results/workflow_fix_report.json" ]; then
            echo "### Fix Report" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
            cat results/workflow_fix_report.json >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "*AI Workflow Collaborator ensures all badges show GREEN ✅*" >> $GITHUB_STEP_SUMMARY
      
      - name: Create issue on failure
        if: failure() && github.event_name == 'schedule'
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 AI Workflow Collaborator detected critical issues';
            const body = `## 🚨 Critical Workflow Issues Detected
            
            The AI Workflow Collaborator has detected critical issues that could not be automatically fixed.
            
            **Date:** ${new Date().toISOString()}
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            ### Action Required
            
            1. Review the workflow health report in the artifacts
            2. Manually fix the issues
            3. Re-run the AI Workflow Collaborator
            
            ### Reports
            
            - Download health report from workflow artifacts
            - Check logs for detailed error messages
            
            ---
            *This issue was automatically created by AI Workflow Collaborator*
            `;
            
            // Check if issue already exists
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'automated,ci/cd,priority: high'
            });
            
            const existingIssue = issues.data.find(issue => issue.title === title);
            
            if (!existingIssue) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['automated', 'ci/cd', 'priority: high']
              });
            }
