name: CI básico para PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
        continue-on-error: false

      - name: Run linters
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. Line length set to 120.
          flake8 scripts/ --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
        continue-on-error: true
        id: lint

      - name: Run tests
        run: python scripts/run_all_tests.py
        continue-on-error: true
        id: test

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const lintStatus = '${{ steps.lint.outcome }}' === 'success' ? '✅ Lint passed' : '❌ Lint failed';
            const testStatus = '${{ steps.test.outcome }}' === 'success' ? '✅ Tests passed' : '❌ Tests failed';
            const body = `Automated validation results:\n\n- ${lintStatus}\n- ${testStatus}\n\n*(Este comentario fue generado automáticamente por el workflow CI)*`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body
            });
