name: Master Workflow Orchestration

on:
  workflow_dispatch:
    inputs:
      run_all:
        description: 'Run all workflows'
        required: false
        default: 'true'
        type: boolean
      run_quantum:
        description: 'Run quantum validations'
        required: false
        default: 'true'
        type: boolean
      run_alternative:
        description: 'Run alternative validations'
        required: false
        default: 'true'
        type: boolean
      run_multi_event:
        description: 'Run multi-event analysis'
        required: false
        default: 'true'
        type: boolean
      run_detector:
        description: 'Run detector analysis'
        required: false
        default: 'true'
        type: boolean
      run_scientific:
        description: 'Run scientific validation'
        required: false
        default: 'true'
        type: boolean
      run_advanced:
        description: 'Run advanced analysis'
        required: false
        default: 'true'
        type: boolean
      run_special:
        description: 'Run special analysis'
        required: false
        default: 'true'
        type: boolean
      run_tests:
        description: 'Run comprehensive tests'
        required: false
        default: 'true'
        type: boolean
  schedule:
    # Run complete suite weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

jobs:
  orchestration-start:
    name: Orchestration Start
    runs-on: ubuntu-latest
    
    steps:
      - name: Workflow orchestration started
        run: |
          echo "## 🎭 Master Workflow Orchestration Started" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Workflows to execute:**" >> $GITHUB_STEP_SUMMARY
          echo "- Quantum Validations: ${{ github.event.inputs.run_quantum || 'true' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Alternative Validations: ${{ github.event.inputs.run_alternative || 'true' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Multi-Event Analysis: ${{ github.event.inputs.run_multi_event || 'true' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Detector Analysis: ${{ github.event.inputs.run_detector || 'true' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Scientific Validation: ${{ github.event.inputs.run_scientific || 'true' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Advanced Analysis: ${{ github.event.inputs.run_advanced || 'true' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Special Analysis: ${{ github.event.inputs.run_special || 'true' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Comprehensive Tests: ${{ github.event.inputs.run_tests || 'true' }}" >> $GITHUB_STEP_SUMMARY
  
  trigger-quantum:
    name: Trigger Quantum Validations
    needs: orchestration-start
    if: github.event.inputs.run_quantum != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger quantum validations workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'quantum-validations.yml',
              ref: context.ref
            });
            console.log('Triggered quantum validations workflow');
  
  trigger-alternative:
    name: Trigger Alternative Validations
    needs: orchestration-start
    if: github.event.inputs.run_alternative != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger alternative validations workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'alternative-validations.yml',
              ref: context.ref
            });
            console.log('Triggered alternative validations workflow');
  
  trigger-multi-event:
    name: Trigger Multi-Event Analysis
    needs: orchestration-start
    if: github.event.inputs.run_multi_event != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger multi-event analysis workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'multi-event-analysis.yml',
              ref: context.ref
            });
            console.log('Triggered multi-event analysis workflow');
  
  trigger-detector:
    name: Trigger Detector Analysis
    needs: orchestration-start
    if: github.event.inputs.run_detector != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger detector analysis workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'detector-analysis.yml',
              ref: context.ref
            });
            console.log('Triggered detector analysis workflow');
  
  trigger-scientific:
    name: Trigger Scientific Validation
    needs: orchestration-start
    if: github.event.inputs.run_scientific != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger scientific validation workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'scientific-validation.yml',
              ref: context.ref
            });
            console.log('Triggered scientific validation workflow');
  
  trigger-advanced:
    name: Trigger Advanced Analysis
    needs: orchestration-start
    if: github.event.inputs.run_advanced != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger advanced analysis workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'advanced-analysis.yml',
              ref: context.ref
            });
            console.log('Triggered advanced analysis workflow');
  
  trigger-special:
    name: Trigger Special Analysis
    needs: orchestration-start
    if: github.event.inputs.run_special != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger special analysis workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'special-analysis.yml',
              ref: context.ref
            });
            console.log('Triggered special analysis workflow');
  
  trigger-tests:
    name: Trigger Comprehensive Tests
    needs: orchestration-start
    if: github.event.inputs.run_tests != 'false'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger comprehensive testing workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'comprehensive-testing.yml',
              ref: context.ref
            });
            console.log('Triggered comprehensive testing workflow');
  
  orchestration-complete:
    name: Orchestration Complete
    needs: [trigger-quantum, trigger-alternative, trigger-multi-event, trigger-detector, trigger-scientific, trigger-advanced, trigger-special, trigger-tests]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Workflow orchestration completed
        run: |
          echo "## ✅ Master Workflow Orchestration Complete" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Completion Time:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All workflow triggers have been dispatched." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Note:** Individual workflow statuses can be viewed in the Actions tab." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🎯 Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Monitor individual workflow runs" >> $GITHUB_STEP_SUMMARY
          echo "2. Review artifacts from each workflow" >> $GITHUB_STEP_SUMMARY
          echo "3. Check validation results in the results/ directory" >> $GITHUB_STEP_SUMMARY
          echo "4. Verify all tests pass (green checks)" >> $GITHUB_STEP_SUMMARY
